site_name: markdown语法详解(基于mkdocs-material) - cyent笔记
site_description: 关于mkdocs-material支持的markdown语法，包括传统语法和扩展语法
site_author: cyent
site_url: https://cyent.github.io/markdown-with-mkdocs-material/

repo_name: 'cyent/markdown-with-mkdocs-material'
repo_url: 'https://github.com/cyent/markdown-with-mkdocs-material'

theme: material

extra:
  palette:
    primary: 'Blue Grey'
    accent: 'Pink'
  feature:
    tabs: false
  social:
    - type: github
      link: https://github.com/cyent
  #font:
    #text: 'Ubuntu'
    #code: 'Ubuntu Mono'

markdown_extensions:
    - admonition
    - codehilite(guess_lang=false,linenums=false)
    - toc(permalink=true)
    - footnotes
    - meta
    - def_list
    - pymdownx.arithmatex
    - pymdownx.betterem(smart_enable=all)
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
        emoji_generator: !!python/name:pymdownx.emoji.to_png
        #emoji_generator: !!python/name:pymdownx.emoji.to_svg
        #emoji_generator: !!python/name:pymdownx.emoji.to_png_sprite
        #emoji_generator: !!python/name:pymdownx.emoji.to_svg_sprite
        #emoji_generator: !!python/name:pymdownx.emoji.to_awesome
        #emoji_generator: !!python/name:pymdownx.emoji.to_alt
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist
    - pymdownx.tilde

extra_javascript:
    - 'js/extra.js'
    - 'js/baidu-tongji.js'
    - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'


pages:
    - 一. 介绍: index.md
    - 二. 安装:
        - 1. 本地环境搭建: install/local.md
        - 2. 发布至GitHub Pages: install/github-pages.md
        - 3. 发布至自己的HTTP Server: install/http-server.md
    - 三. 语法:
        - 1. 语法总览: syntax/main.md
        - 2. 标题: syntax/headline.md
        - 3. 段落: syntax/paragraph.md
        - 4. 引用: syntax/quote.md
        - 5. 代码:
            - 5.1. 行内: syntax/code_inline.md
            - 5.2. 区块: syntax/code_block.md
            - 5.3. 高亮: syntax/code_highlight.md
        - 6. 字体样式:
            - 6.1. 斜体,粗体,粗斜体: syntax/font_stress.md
            - 6.2. 上标,下标: syntax/font_updown.md
            - 6.3. 下划线: syntax/font_underline.md
            - 6.4. 横线: syntax/font_line.md
            - 6.5. 下划线+横线: syntax/font_underline_line.md
        - 7. 列表:
            - 7.1. 无序列表: syntax/list_noseq.md
            - 7.2. 有序列表: syntax/list_seq.md
            - 7.3. 任务列表: syntax/list_task.md
        - 8. 分割线: syntax/cutline.md
        - 9. 链接:
            - 9.1. 普通链接: syntax/link_normal.md
            - 9.2. 自动链接: syntax/link_auto.md
            - 9.3. 锚点提示: syntax/link_anchor.md
        - 10. 图片:
            - 10.1. 行内式: syntax/image_inline.md
            - 10.2. 参考式: syntax/image_index.md
        - 11. 转义: syntax/escape.md
        - 12. 高亮:
            - 12.1. 代码高亮: syntax/highlight_code.md
            - 12.2. 背景高亮: syntax/highlight_background.md
        - 13. 注解:
            - 13.1. 介绍: syntax/note_main.md
            - 13.2. 完整格式: syntax/note_full.md
            - 13.3. 空标题: syntax/note_empty-title.md
            - 13.4. 无标题: syntax/note_none-title.md
            - 13.5. 无类型: syntax/note_none-type.md
            - 13.6. 折叠: syntax/note_details.md
            - 13.7. 11种颜色样式: syntax/note_style.md
            - 13.8. 嵌套: syntax/note_nest.md
        - 14. 脚注: syntax/footnote.md
        - 15. 元信息: syntax/meta.md
        - 16. 数学公式:
            - 16.1. 介绍: syntax/math_main.md
            - 16.2. 导入js: syntax/math_js.md
            - 16.3. 用法: syntax/math_usage.md
        - 17. emoji:
            - 17.1. 介绍: syntax/emoji_main.md
            - 17.2. 工作原理: syntax/emoji_principle.md
            - 17.3. 最佳实践: syntax/emoji_usage.md
        - 18. 特殊符号: syntax/symbol.md
        - 19. 嵌套:
            - 19.1. 介绍: syntax/nest_main.md
            - 19.2. 注解-注解: syntax/nest_note_note.md
            - 19.3. 列表-列表: syntax/nest_list_list.md
            - 19.4. 引用-引用: syntax/nest_quote_quote.md
            - 19.5. 注解-代码块: syntax/nest_note_code.md
            - 19.6. 列表-代码块: syntax/nest_list_code.md
            - 19.7. 引用-代码块: syntax/nest_quote_code.md
            - 19.8. 黄色区块-代码: syntax/nest_yellow_code.md
            - 19.9. 绿色区块-代码: syntax/nest_green_code.md
            - 19.10. 红色区块-代码: syntax/nest_red_code.md
            - 19.11. 绿接红区块-代码: syntax/nest_greenred_code.md
            - 19.12. 注解-列表-引用: syntax/nest_note_list_quote.md
            - 19.13. 列表-列表-引用: syntax/nest_list_list_quote.md
            - 19.14. 引用-引用-代码: syntax/nest_quote_quote_code.md
    - 四. 附录:
        - 1. 支持代码高亮的语言: appendix/pygments.md
        - 2. emojione全名短名映射表: appendix/emoji_shortname.md
        - 3. 添加百度统计: appendix/baidu_tongji.md
        - 4. 配色: appendix/color.md
        - 5. 模块介绍: appendix/module.md
    - 五. 使用建议: recommend.md
